// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWXWBaUFJhlLy4jIAxR9S_mI5y_QbmY4I',
    appId: '1:218758514469:android:74d17cdb46d041ad3b3ccc',
    messagingSenderId: '218758514469',
    projectId: 'loan-guru-6a6e1',
    // storageBucket: 'clickinnovate-7daeb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWXWBaUFJhlLy4jIAxR9S_mI5y_QbmY4I',
    appId: '1:218758514469:ios:bcf4adf838d14f963b3ccc',
    messagingSenderId: '218758514469',
    projectId: 'loan-guru-6a6e1',
  );

}
