class CreditCountryController {
  static List<String> nameOfCountryList = [
    "Andorra",
    "United Arab Emirates",
    "Afghanistan",
    "Antigua and Barbuda",
    "Anguilla",
    "Albania",
    "Armenia",
    "Angola",
    "Antarctica",
    "Argentina",
    "American Samoa",
    "Austria",
    "Australia",
    "Aruba",
    "Aland Islands",
    "Azerbaijan",
    "Bosnia and Herzegovina",
    "Barbados",
    "Bangladesh",
    "Belgium",
    "Burkina Faso",
    "Bulgaria",
    "Bahrain",
    "Burundi",
    "Benin",
    "Saint Barthelemy",
    "Bermuda",
    "Brunei Darussalam",
    "Bolivia",
    "Bonaire",
    "Brazil",
    "Bahamas",
    "Bhutan",
    "Bouvet Island",
    "Botswana",
    "Belarus",
    "Belize",
    "Canada",
    "Cocos(Keeling)Lslands",
    "Congo,Democratic Republic",
    "Central African Republic",
    "Congo",
    "Switzerland",
    "Ivory Coast",
    "Cook Islands",
    "Chile",
    "Cameroon",
    "China",
    "Colombia",
    "Costa Rica",
    "Cuba",
    "Cape Verde",
    "Curacao",
    "Christmas Island",
    "Cyprus",
    "Czech Republic",
    "Germany",
    "Djibouti",
    "Denmark",
    "Dominica",
    "Dominican Republic",
    "Algeria",
    "Ecuador",
    "Estonia",
    "Egypt",
    "Western Sahara",
    "Eritrea",
    "Spain",
    "Ethiopia",
    "Finland",
    "Fiji",
    "Falkland Islands(Malvinas)",
    "Micronesia",
    "Faroe Lslands",
    "France",
    "Gabon",
    "United Kingdom",
    "Grenada",
    "Georgia",
    "French Guiana",
    "Guernsey",
    "Ghana",
    "Gibraltar",
    "Greenland",
    "Gambia",
    "Guinea",
    "Guadeloupe",
    "Equatorial Guinea",
    "Greece",
    "South Georgia and the South",
    "Guatemala",
    "Guam",
    "Guinea-Bissau",
    "Guyana",
    "Hong Kong",
    "Heard Lsland",
    "Honduras",
    "Croatia",
    "Haiti",
    "Hungary",
    "Indonesia",
    "Ireland",
    "Israel",
    "Isle of Man",
    "India",
    "British Indian Ocean Territory",
    "Iraq",
    "Iran",
    "Iceland",
    "Italy",
    "Jersey",
    "Jamaica",
    "Jordan",
    "Japan",
    "Kenya",
    "Kyrguzstan",
    "Cambodia",
    "Kiribati",
    "Comoros",
    "Saint Kitts and Nevis",
    "North Korea",
    "South Korea",
    "Kuwait",
    "Cayman Lslands",
    "Kazakhstan",
    "Lao People'sDemocratic",
    "Lebanon",
    "Saint Lucia",
    "Liechtenstein",
    "Sri Lanka",
    "Liberia",
    "Lesotho",
    "Lithuania",
    "Luxembourg",
    "Latvia",
    "Libyan Arab Jamahiriya",
    "Morocco",
    "Monaco",
    "Moldova",
    "Montenegro",
    "Saint Martin",
    "Madagascar",
    "Marshall Islands",
    "Macedonia",
    "Mali",
    "Myanmar",
    "Mongolia",
    "Macao",
    "Northern Mariana lslands",
    "Martinigue",
    "Mauritania",
    "Montserrat",
    "Malta",
    "Mauritius",
    "Maldives",
    "Malawi",
    "Mexico",
    "Malaysia",
    "Mozambique",
    "Namibia",
    "New Caledonia",
    "Niger",
    "Norfolk Island",
    "Nigeria",
    "Nicaragua",
    "Netherlands",
    "Norway",
    "Nepal",
    "Nauru",
    "Niue",
    "New Zealand",
    "Oman",
    "Panama",
    "Peru",
    "French Polynesia",
    "Papua New Guinea",
    "Philippines",
    "Pakistan",
    "Poland",
    "Saint Pierre and Miquelon",
    "Pitcairn",
    "Puerto Rico",
    "Palestinian Territory",
    "Portugal",
    "Palau",
    "Paraguay",
    "Qatar",
    "Reunion",
    "Romania",
    "Serbia",
    "Russia",
    "Rwanda",
    "Saudi Arabia",
    "Solomon Islands",
    "Seychelles",
    "Sudan",
    "Sweden",
    "Singapore",
    "Saint Helena",
    "Slovenia",
    "Svalbard and Jan Mayen",
    "Slovakia",
    "Sierra Leone",
    "San Marino",
    "Senegal",
    "Somalia",
    "Suriname",
    "South Sudan",
    "Sao Tome and Principe",
    "Ei Salvador",
    "Sint Maarten",
    "Syrian Arab Republic",
    "Swaziland",
    "Turks and Caicos Islands",
    "Chad",
    "French Southern Territories",
    "Togo",
    "Thailand",
    "Tajikistan",
    "Tokelau",
    "East Timor",
    "Turkmenistan",
    "Tunisia",
    "Tonga",
    "Turkey",
    "Trinidad and Tobago",
    "Tuvalu",
    "Taiwan",
    "Tanzania,United",
    "Ukraine",
    "Uganda",
    "US.Minor Outlying Islands",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Holy See(Vatican City state)",
    "Saint Vicent",
    "Venezuela",
    "Virgin Islands,British",
    "Virgin Islands,U.S",
    "Viet Nam",
    "Vanuatu",
    "Wallis and Futuna",
    "Samoa",
    "Kosovo",
    "Yemen",
    "Mayotte",
    "South Africa",
    "Zambia",
    "Zimbabwe",
  ];
  static List<String> imageOfCountry = [
    "Flag_Andorra.webp",
    "flag_ae.png",
    "flag_af.png",
    "flag_ag.png",
    "flag_ai.png",
    "flag_al.png",
    "flag_am.png",
    "flag_ao.png",
    "flag_aq.png",
    "flag_ar.png",
    "flag_as.png",
    "flag_at.png",
    "flag_au.png",
    "flag_aw.png",
    "flag_ax.png",
    "flag_az.png",
    "flag_ba.png",
    "flag_bb.png",
    "flag_bd.png",
    "flag_be.png",
    "flag_bf.png",
    "flag_bg.png",
    "flag_bh.png",
    "flag_bi.png",
    "flag_bj.png",
    "flag_bl.png",
    "flag_bm.png",
    "flag_bn.png",
    "flag_bo.png",
    "flag_bq.png",
    "flag_br.png",
    "flag_bs.png",
    "flag_bt.webp",
    "flag_bv.png",
    "flag_bw.png",
    "flag_by.png",
    "flag_bz.webp",
    "flag_ca.png",
    "flag_cc.png",
    "flag_cd.png",
    "flag_cf.png",
    "flag_cg.png",
    "flag_ch.png",
    "flag_ci.png",
    "flag_ck.png",
    "flag_cl.png",
    "flag_cm.png",
    "flag_cn.png",
    "flag_co.png",
    "flag_cr.webp",
    "flag_cu.png",
    "flag_cv.png",
    "flag_cw.png",
    "flag_cx.png",
    "flag_cy.png",
    "flag_cz.png",
    "flag_de.png",
    "flag_dj.png",
    "flag_dk.png",
    "flag_dm.png",
    "flag_do.webp",
    "flag_dz.png",
    "flag_ec.webp",
    "flag_ee.png",
    "flag_eg.png",
    "flag_eh.png",
    "flag_er.png",
    "flag_es.webp",
    "flag_et.png",
    "flag_fi.png",
    "flag_fj.png",
    "flag_fk.webp",
    "flag_fm.png",
    "flag_fo.png",
    "flag_fr.png",
    "flag_ga.png",
    "flag_gb.png",
    "flag_gd.png",
    "flag_ge.png",
    "flag_gf.png",
    "flag_gg.png",
    "flag_gh.png",
    "flag_gi.png",
    "flag_gl.png",
    "flag_gm.png",
    "flag_gn.png",
    "flag_gp.png",
    "flag_gq.png",
    "flag_gr.png",
    "flag_gs.webp",
    "flag_gt.webp",
    "flag_gu.webp",
    "flag_gw.png",
    "flag_gy.png",
    "flag_hk.png",
    "flag_hm.png",
    "flag_hn.png",
    "flag_hr.png",
    "flag_ht.webp",
    "flag_hu.png",
    "flag_id.png",
    "flag_ie.png",
    "flag_il.png",
    "flag_im.webp",
    "flag_in.png",
    "flag_io.png",
    "flag_iq.png",
    "flag_ir.png",
    "flag_is.png",
    "flag_it.png",
    "flag_je.png",
    "flag_jm.png",
    "flag_jo.png",
    "flag_jp.png",
    "flag_ke.png",
    "flag_kg.png",
    "flag_kh.png",
    "flag_ki.png",
    "flag_km.png",
    "flag_kn.png",
    "flag_kp.png",
    "flag_kr.png",
    "flag_kw.png",
    "flag_ky.png",
    "flag_kz.png",
    "flag_la.png",
    "flag_lb.png",
    "flag_lc.png",
    "flag_li.png",
    "flag_lk.png",
    "flag_lr.png",
    "flag_ls.png",
    "flag_lt.png",
    "flag_lu.png",
    "flag_lv.png",
    "flag_ly.png",
    "flag_ma.png",
    "flag_mc.png",
    "flag_md.png",
    "flag_me.webp",
    "flag_mf.png",
    "flag_mg.png",
    "flag_mh.png",
    "flag_mk.png",
    "flag_ml.png",
    "flag_mm.png",
    "flag_mn.png",
    "flag_mo.png",
    "flag_mp.webp",
    "flag_mq.png",
    "flag_mr.png",
    "flag_ms.png",
    "flag_mt.webp",
    "flag_mu.png",
    "flag_mv.png",
    "flag_mw.png",
    "flag_mx.webp",
    "flag_my.png",
    "flag_mz.png",
    "flag_na.png",
    "flag_nc.png",
    "flag_ne.png",
    "flag_nf.png",
    "flag_ng.png",
    "flag_ni.webp",
    "flag_nl.png",
    "flag_no.png",
    "flag_np.png",
    "flag_nr.png",
    "flag_nu.png",
    "flag_nz.png",
    "flag_om.png",
    "flag_pa.png",
    "flag_pe.png",
    "flag_pf.png",
    "flag_pg.png",
    "flag_ph.png",
    "flag_pk.png",
    "flag_pl.png",
    "flag_pm.png",
    "flag_pn.png",
    "flag_pr.png",
    "flag_ps.png",
    "flag_pt.webp",
    "flag_pw.png",
    "flag_py.png",
    "flag_qa.png",
    "flag_re.png",
    "flag_ro.png",
    "flag_rs.webp",
    "flag_ru.png",
    "flag_rw.png",
    "flag_sa.png",
    "flag_sb.png",
    "flag_sc.png",
    "flag_sd.png",
    "flag_se.png",
    "flag_sg.png",
    "flag_sh.png",
    "flag_si.png",
    "flag_sj.png",
    "flag_sk.png",
    "flag_sl.png",
    "flag_sm.webp",
    "flag_sn.png",
    "flag_so.png",
    "flag_sr.png",
    "flag_ss.png",
    "flag_st.png",
    "flag_sv.webp",
    "flag_sx.webp",
    'flag_sy.png',
    "flag_sz.png",
    "flag_tc.png",
    "flag_td.png",
    "flag_tf.png",
    "flag_tg.png",
    "flag_th.png",
    "flag_tj.png",
    "flag_tk.png",
    "flag_tl.png",
    "flag_tm.webp",
    "flag_tn.png",
    "flag_to.png",
    "turkey.png",
    "trinidad.png",
    "flag_tv.png",
    "flag_tw.png",
    'flag_tz.png',
    "flag_ua.png",
    "flag_ug.png",
    "flag_um.png",
    "flag_us.png",
    "flag_uy.png",
    "flag_uz.png",
    "flag_va.webp",
    "flag_vc.png",
    "flag_ve.png",
    "flag_vg.png",
    "flag_vi.png",
    "flag_vn.png",
    "flag_vu.png",
    "flag_wf.png",
    "flag_ws.png",
    "flag_xk.png",
    "flag_ye.png",
    "flag_yt.png",
    "flag_za.png",
    "flag_zm.png",
    "flag_zw.png",
  ];
}
